/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soal1apotik;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class apotik extends javax.swing.JFrame {

    /**
     * Creates new form apotik
     */
    public apotik() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pKanan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        gejala = new javax.swing.JComboBox<>();
        cek = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pTengah = new javax.swing.JPanel();
        rak1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        iBetadine = new javax.swing.JLabel();
        iHansaplast = new javax.swing.JLabel();
        iHIC = new javax.swing.JLabel();
        iKonidin = new javax.swing.JLabel();
        iAntimo = new javax.swing.JLabel();
        rak2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        iVitC = new javax.swing.JLabel();
        iParacetamol = new javax.swing.JLabel();
        iPromag = new javax.swing.JLabel();
        iSangobion = new javax.swing.JLabel();
        iTolakAngin = new javax.swing.JLabel();
        pBawah = new javax.swing.JPanel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAtas.setBackground(new java.awt.Color(22, 66, 60));

        jLabel1.setFont(new java.awt.Font("Schadow BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 239, 236));
        jLabel1.setText("APOTEK MINI");
        pAtas.add(jLabel1);

        getContentPane().add(pAtas, java.awt.BorderLayout.PAGE_START);

        pKanan.setBackground(new java.awt.Color(233, 239, 236));
        pKanan.setPreferredSize(new java.awt.Dimension(215, 0));
        pKanan.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel11.setText("Pilih Gejala :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        pKanan.add(jLabel11, gridBagConstraints);

        gejala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mual dan mabuk perjalanan", "Menyembuhkan infeksi pada luka", "Plester melindungi luka", "Krim untuk nyeri otot", "Meredakan batuk ", "Menjaga daya tahan tubuh", "Menurunkan demam ", "Mengurangi mual dan kembung", "Penambah darah", "Mengatasi masuk angin" }));
        gejala.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        pKanan.add(gejala, gridBagConstraints);

        cek.setText("Cek");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        pKanan.add(cek, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel12.setText("NB :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        pKanan.add(jLabel12, gridBagConstraints);

        jLabel18.setText("Klik gambar untuk lebih detail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        pKanan.add(jLabel18, gridBagConstraints);

        getContentPane().add(pKanan, java.awt.BorderLayout.LINE_END);

        pTengah.setLayout(new java.awt.GridLayout(2, 1));

        rak1.setBackground(new java.awt.Color(106, 156, 137));
        rak1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Antimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("Betadine");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("Hansaplast");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("Hot In Cream");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setText("Konidin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(jLabel8, gridBagConstraints);

        iBetadine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/betadine.png"))); // NOI18N
        iBetadine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBetadineMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(iBetadine, gridBagConstraints);

        iHansaplast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/hansaplas.png"))); // NOI18N
        iHansaplast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iHansaplastMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(iHansaplast, gridBagConstraints);

        iHIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/hotincream.png"))); // NOI18N
        iHIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iHICMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(iHIC, gridBagConstraints);

        iKonidin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/konidin.jpg"))); // NOI18N
        iKonidin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iKonidinMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(iKonidin, gridBagConstraints);

        iAntimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/antimo.png"))); // NOI18N
        iAntimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iAntimoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak1.add(iAntimo, gridBagConstraints);

        pTengah.add(rak1);

        rak2.setBackground(new java.awt.Color(196, 218, 210));
        rak2.setLayout(new java.awt.GridBagLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel13.setText("Vitacimin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel14.setText("Paracetamol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel15.setText("Promag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel16.setText("Sangobion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel17.setText("Tolak Angin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(jLabel17, gridBagConstraints);

        iVitC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/vitc.png"))); // NOI18N
        iVitC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iVitCMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(iVitC, gridBagConstraints);

        iParacetamol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/paracetamol.png"))); // NOI18N
        iParacetamol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iParacetamolMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(iParacetamol, gridBagConstraints);

        iPromag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/promag.png"))); // NOI18N
        iPromag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iPromagMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(iPromag, gridBagConstraints);

        iSangobion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/sangobion.png"))); // NOI18N
        iSangobion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSangobionMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(iSangobion, gridBagConstraints);

        iTolakAngin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soal1apotik/tolakangin.png"))); // NOI18N
        iTolakAngin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iTolakAnginMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        rak2.add(iTolakAngin, gridBagConstraints);

        pTengah.add(rak2);

        getContentPane().add(pTengah, java.awt.BorderLayout.CENTER);

        pBawah.setBackground(new java.awt.Color(22, 66, 60));
        pBawah.setPreferredSize(new java.awt.Dimension(0, 70));

        exit.setBackground(new java.awt.Color(204, 0, 0));
        exit.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBawahLayout = new javax.swing.GroupLayout(pBawah);
        pBawah.setLayout(pBawahLayout);
        pBawahLayout.setHorizontalGroup(
            pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBawahLayout.createSequentialGroup()
                .addContainerGap(862, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pBawahLayout.setVerticalGroup(
            pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBawahLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(exit)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iAntimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iAntimoMouseClicked
        // TODO add your handling code here:
        ImageIcon Antimo = new ImageIcon(getClass().getResource("antimo.png"));
        JOptionPane.showMessageDialog(null, "Cocok untuk yang mempunyai gejala mabuk \n"
                + "perjalanan, mual, dan muntah", 
                "Antimo", JOptionPane.WIDTH,Antimo);
    }//GEN-LAST:event_iAntimoMouseClicked

    private void iBetadineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iBetadineMouseClicked
        // TODO add your handling code here:
        ImageIcon Betadin = new ImageIcon(getClass().getResource("betadine.png"));
        JOptionPane.showMessageDialog(null, "Antiseptik yang bermanfaat untuk mencegah \n"
                + "pertumbuhan dan membunuh kuman penyebab infeksi", 
                "Betadine", JOptionPane.WIDTH, Betadin);
    }//GEN-LAST:event_iBetadineMouseClicked

    private void iHansaplastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iHansaplastMouseClicked
        // TODO add your handling code here:
        ImageIcon Hansaplast = new ImageIcon(getClass().getResource("hansaplas.png"));
        JOptionPane.showMessageDialog(null, "Plester yang melindungi segala jenis luka ringan \n"
                + "dari kotoran dan bakteri", 
                "Hansaplast", JOptionPane.WIDTH, Hansaplast);
    }//GEN-LAST:event_iHansaplastMouseClicked

    private void iHICMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iHICMouseClicked
        // TODO add your handling code here:
        ImageIcon HIC = new ImageIcon(getClass().getResource("hotincream.png"));
        JOptionPane.showMessageDialog(null, "Krim analgesik yang berguna untuk mengatasi capek, pegal, \n"
                + "dan nyeri otot yang mengganggu aktivitas harian, \n"
                + "masuk angin, perut kembung dan sakit kepala", 
                "Hot In Cream", JOptionPane.WIDTH, HIC);
    }//GEN-LAST:event_iHICMouseClicked

    private void iKonidinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iKonidinMouseClicked
        // TODO add your handling code here:
        ImageIcon Konidin = new ImageIcon(getClass().getResource("konidin.jpg"));
        JOptionPane.showMessageDialog(null, "Obat yang digunakan untuk mengatasi gejala batuk \n"
                + "yang bisa terjadi karena alergi, flu, \n"
                + "atau gejala bronkitis", 
                "Konidin", JOptionPane.WIDTH, Konidin);
    }//GEN-LAST:event_iKonidinMouseClicked

    private void iVitCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iVitCMouseClicked
        // TODO add your handling code here:
        ImageIcon VC = new ImageIcon(getClass().getResource("vitc.png"));
        JOptionPane.showMessageDialog(null, " vitamin yang memiliki banyak manfaat untuk tubuh, \n"
                + "seperti meningkatkan daya tahan tubuh, \n"
                + "memperkuat jaringan tubuh, \n"
                + "dan mempercepat pemulihan saat sakit", 
                "Vitamin C", JOptionPane.WIDTH, VC);
    }//GEN-LAST:event_iVitCMouseClicked

    private void iParacetamolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iParacetamolMouseClicked
        // TODO add your handling code here:
        ImageIcon Paracetamol = new ImageIcon(getClass().getResource("paracetamol.png"));
        JOptionPane.showMessageDialog(null, "Cocok untuk yang mempunyai gejala \n"
                + "rasa sakit pada kepala, sakit gigi, \n"
                + "dan menurunkan demam", 
                "Paracetamol", JOptionPane.WIDTH, Paracetamol);
    }//GEN-LAST:event_iParacetamolMouseClicked

    private void iPromagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iPromagMouseClicked
        // TODO add your handling code here:
        ImageIcon Promag = new ImageIcon(getClass().getResource("promag.png"));
        JOptionPane.showMessageDialog(null, "Obat untuk mengurangi gejala-gejala \n"
                + "seperti mual, nyeri lambung, nyeri ulu hati, \n"
                + "kembung, dan perasaan penuh pada lambunng", 
                "Promag", JOptionPane.WIDTH, Promag);
    }//GEN-LAST:event_iPromagMouseClicked

    private void iSangobionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSangobionMouseClicked
        // TODO add your handling code here:
        ImageIcon Sangobion = new ImageIcon(getClass().getResource("sangobion.png"));
        JOptionPane.showMessageDialog(null, "Obat yang mengandung vitamin dan \n"
                + "zat besi penambah darah", 
                "Sangobion", JOptionPane.WIDTH, Sangobion);
    }//GEN-LAST:event_iSangobionMouseClicked

    private void iTolakAnginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iTolakAnginMouseClicked
        // TODO add your handling code here:
        ImageIcon TolakAnging = new ImageIcon(getClass().getResource("tolakangin.png"));
        JOptionPane.showMessageDialog(null, "bat herbal yang dapat membantu meredakan gejala masuk angin \n"
                + "dan meningkatkan daya tahan tubuh", 
                "Tolak Angin", JOptionPane.WIDTH, TolakAnging);
    }//GEN-LAST:event_iTolakAnginMouseClicked

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Ingin keluar?","Keluar",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_exitActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String) gejala.getSelectedItem();
            // Kondisi if-else untuk setiap item
            if (selectedOption.equals("Mual dan mabuk perjalanan")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih obat Antimo", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Menyembuhkan infeksi pada luka")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih obat Betadine", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Plester melindungi luka")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Hansaplast", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Krim untuk nyeri otot")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Hot in Cream", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Meredakan batuk ")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih konidin", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Menjaga daya tahan tubuh")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Vitacimin", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Menurunkan demam ")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Paracetamol", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Mengurangi mual dan kembung")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Promag", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Penambah darah")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Sangobion", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("Mengatasi masuk angin")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih Tolak Angin", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } 
    }//GEN-LAST:event_cekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apotik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apotik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apotik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apotik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apotik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cek;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> gejala;
    private javax.swing.JLabel iAntimo;
    private javax.swing.JLabel iBetadine;
    private javax.swing.JLabel iHIC;
    private javax.swing.JLabel iHansaplast;
    private javax.swing.JLabel iKonidin;
    private javax.swing.JLabel iParacetamol;
    private javax.swing.JLabel iPromag;
    private javax.swing.JLabel iSangobion;
    private javax.swing.JLabel iTolakAngin;
    private javax.swing.JLabel iVitC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pAtas;
    private javax.swing.JPanel pBawah;
    private javax.swing.JPanel pKanan;
    private javax.swing.JPanel pTengah;
    private javax.swing.JPanel rak1;
    private javax.swing.JPanel rak2;
    // End of variables declaration//GEN-END:variables
}
