/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokoroti;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class pemesananRoti extends javax.swing.JFrame {

    /**
     * Creates new form pemesananRoti
     */
    public pemesananRoti() {
        initComponents();
        this.setLocationRelativeTo(null);
        hRamazan.setEditable(false);
        hBazlama.setEditable(false);
        hSimit.setEditable(false);
        hYufka.setEditable(false);
        hPita.setEditable(false);
        hGozleme.setEditable(false);
        hOriginal.setEditable(false);
        hCokelat.setEditable(false);
        hKeju.setEditable(false);
        jumlah.setEditable(false);
        kembali.setEditable(false);
        txttotal.setEditable(false);
        txtdiskon.setEditable(false);
        stlhDiskon.setEditable(false);
        
        cash.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                hitung();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        topping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ramazan = new javax.swing.JRadioButton();
        bazlama = new javax.swing.JRadioButton();
        simit = new javax.swing.JRadioButton();
        yufka = new javax.swing.JRadioButton();
        pita = new javax.swing.JRadioButton();
        gozleme = new javax.swing.JRadioButton();
        hRamazan = new javax.swing.JTextField();
        hBazlama = new javax.swing.JTextField();
        hSimit = new javax.swing.JTextField();
        hYufka = new javax.swing.JTextField();
        hPita = new javax.swing.JTextField();
        hGozleme = new javax.swing.JTextField();
        original = new javax.swing.JRadioButton();
        cokelat = new javax.swing.JRadioButton();
        keju = new javax.swing.JRadioButton();
        hOriginal = new javax.swing.JTextField();
        hCokelat = new javax.swing.JTextField();
        hKeju = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        kurang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        stlhDiskon = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 114, 116));

        jPanel2.setBackground(new java.awt.Color(178, 165, 155));

        jPanel3.setBackground(new java.awt.Color(222, 208, 182));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Turkish Bakery");

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel12.setText("Menjual Roti Khas Turki - Berbagai Topping  - Dapatkan Diskon");

        jPanel6.setBackground(new java.awt.Color(222, 208, 182));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\roti2-removebg-preview (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(222, 208, 182));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\roti1-removebg-preview (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(124, 124, 124)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(250, 238, 209));

        jLabel1.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel1.setText("Menu Roti");

        jLabel3.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel3.setText("Topping");

        menu.add(ramazan);
        ramazan.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        ramazan.setText("Ramazan Pides");

        menu.add(bazlama);
        bazlama.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        bazlama.setText("Bazlama");

        menu.add(simit);
        simit.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        simit.setText("Simit");

        menu.add(yufka);
        yufka.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        yufka.setText("Yufka");

        menu.add(pita);
        pita.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        pita.setText("Pita");

        menu.add(gozleme);
        gozleme.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        gozleme.setText("Gozleme");

        hRamazan.setText("Rp.10.000,00");

        hBazlama.setText("Rp.12.000,00");

        hSimit.setText("Rp.15.000,00");

        hYufka.setText("Rp.20.000,00");

        hPita.setText("Rp.25.000,00");

        hGozleme.setText("Rp.30.000,00");

        topping.add(original);
        original.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        original.setText("Original");

        topping.add(cokelat);
        cokelat.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        cokelat.setText("Cokelat");

        topping.add(keju);
        keju.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        keju.setText("Keju");

        hOriginal.setText("Rp. - ");

        hCokelat.setText("Rp.5.000,00");

        hKeju.setText("Rp.6.000,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ramazan)
                            .addComponent(bazlama)
                            .addComponent(simit)
                            .addComponent(yufka)
                            .addComponent(pita)
                            .addComponent(gozleme)
                            .addComponent(original)
                            .addComponent(cokelat)
                            .addComponent(keju))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hGozleme, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hPita, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hYufka, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hSimit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hBazlama, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hRamazan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hCokelat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hKeju, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ramazan)
                    .addComponent(hRamazan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bazlama)
                    .addComponent(hBazlama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simit)
                    .addComponent(hSimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yufka)
                    .addComponent(hYufka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pita)
                    .addComponent(hPita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gozleme)
                    .addComponent(hGozleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(original)
                    .addComponent(hOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokelat)
                    .addComponent(hCokelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keju)
                    .addComponent(hKeju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 238, 194));

        jLabel2.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel2.setText("Jumlah");

        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jumlah.setText("0");
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel4.setText("Cash");

        jLabel5.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        jLabel5.setText("Rp.");

        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel8.setText("______________________________");

        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        jLabel9.setText("Rp.");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel7.setText("Kembali");

        jLabel6.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        jLabel6.setText("Rp.");

        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel15.setText("Diskon");

        jLabel16.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        jLabel16.setText("Rp.");

        txtdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiskonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel17.setText("Nominal  Setelah Diskon");

        jLabel18.setFont(new java.awt.Font("STXihei", 0, 13)); // NOI18N
        jLabel18.setText("Rp.");

        stlhDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stlhDiskonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Humnst777 BT", 0, 16)); // NOI18N
        jLabel19.setText("Nominal  ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(reset)
                .addGap(18, 18, 18)
                .addComponent(keluar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cash, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(kembali)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txttotal))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(stlhDiskon))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurang)
                    .addComponent(total)
                    .addComponent(tambah))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(stlhDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluar)
                    .addComponent(reset))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void hitung() {
        try {
            double hargasetelahdiskon = Double.parseDouble(stlhDiskon.getText());
            double bayar = Double.parseDouble(cash.getText());
            double kembalian = bayar - hargasetelahdiskon;

            if (kembalian >= 0) {
                kembali.setText(String.valueOf(kembalian));
            } else {
                kembali.setText("Uang Tidak Cukup");
            }
        } catch (NumberFormatException e) {
            kembali.setText("Input berupa angka");
        }
    }
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        int Jumlah = Integer.parseInt(jumlah.getText());
        if(menu.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Menu tidak boleh kosong !");
        } else if (topping.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Topping tidak boleh kosong !");
        } else {
            Jumlah++;
        }
       
        jumlah.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_tambahActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        int Jumlah = Integer.parseInt(jumlah.getText());
        if (Jumlah <= 0) {
            JOptionPane.showMessageDialog(null, "jumlah tidak boleh kurang dari 0");
        } else {
           Jumlah--;
        }
     
        jumlah.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_kurangActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        if (menu.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Mohon pilih salah satu menu terlebih dahulu!");
        } else if (topping.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Mohon pilih salah satu topping terlebih dahulu!");
        } else if (jumlah.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Mohon masukkan jumlah roti yang ingin dipesan!");
        } else {
            double harga = 0;
            double diskon = 0;
            
            if (ramazan.isSelected()){
                String jumlahpesanan = jumlah.getText();
                harga += 10000 * Integer.parseInt(jumlahpesanan);
                if (original.isSelected()){
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                } else if (cokelat.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (keju.isSelected()){
                    harga += 6000 * Integer.parseInt(jumlahpesanan);
                } 
                txttotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        stlhDiskon.setText(String.valueOf(harga));
                    } else if (harga > 200000){
                        diskon = harga * 0.10;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                    } else {
                        txtdiskon.setText("0");
                        stlhDiskon.setText(String.valueOf(harga));
                    }
            }
            
            if (bazlama.isSelected()){
                String jumlahpesanan = jumlah.getText();
                harga += 12000 * Integer.parseInt(jumlahpesanan);
                if (original.isSelected()){
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                } else if (cokelat.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (keju.isSelected()){
                    harga += 6000 * Integer.parseInt(jumlahpesanan);
                } 
                txttotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        stlhDiskon.setText(String.valueOf(harga));
                    } else {
                        txtdiskon.setText("0");
                        stlhDiskon.setText(String.valueOf(harga));
                    }
            }
            
            if (simit.isSelected()){
                String jumlahpesanan = jumlah.getText();
                harga += 15000 * Integer.parseInt(jumlahpesanan);
                if (original.isSelected()){
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                } else if (cokelat.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (keju.isSelected()){
                    harga += 6000 * Integer.parseInt(jumlahpesanan);
                } 
                txttotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        stlhDiskon.setText(String.valueOf(harga));
                    } else {
                        txtdiskon.setText("0");
                        stlhDiskon.setText(String.valueOf(harga));
                    }
            }
            
            if (yufka.isSelected()){
                String jumlahpesanan = jumlah.getText();
                harga += 20000 * Integer.parseInt(jumlahpesanan);
                if (original.isSelected()){
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                } else if (cokelat.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (keju.isSelected()){
                    harga += 6000 * Integer.parseInt(jumlahpesanan);
                } 
                txttotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        stlhDiskon.setText(String.valueOf(harga));
                    } else {
                        txtdiskon.setText("0");
                        stlhDiskon.setText(String.valueOf(harga));
                    }
            }
            
            if (pita.isSelected()){
                String jumlahpesanan = jumlah.getText();
                harga += 25000 * Integer.parseInt(jumlahpesanan);
                if (original.isSelected()){
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                } else if (cokelat.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (keju.isSelected()){
                    harga += 6000 * Integer.parseInt(jumlahpesanan);
                } 
                txttotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        stlhDiskon.setText(String.valueOf(harga));
                    } else {
                        txtdiskon.setText("0");
                        stlhDiskon.setText(String.valueOf(harga));
                    }
            }
            
            if (gozleme.isSelected()){
                String jumlahpesanan = jumlah.getText();
                harga += 30000 * Integer.parseInt(jumlahpesanan);
                if (original.isSelected()){
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                } else if (cokelat.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (keju.isSelected()){
                    harga += 6000 * Integer.parseInt(jumlahpesanan);
                } 
                txttotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        txtdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        stlhDiskon.setText(String.valueOf(harga));
                    } else {
                        txtdiskon.setText("0");
                        stlhDiskon.setText(String.valueOf(harga));
                    }
            }
        }
    }//GEN-LAST:event_totalActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        menu.clearSelection();
        topping.clearSelection();
        jumlah.setText("0");
        cash.setText("");
        kembali.setText("");
        txttotal.setText("");
        txtdiskon.setText("");
        stlhDiskon.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Akhiri Pesanan?","Keluar",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void txtdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiskonActionPerformed

    private void stlhDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stlhDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stlhDiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesananRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesananRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesananRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesananRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesananRoti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bazlama;
    private javax.swing.JTextField cash;
    private javax.swing.JRadioButton cokelat;
    private javax.swing.JRadioButton gozleme;
    private javax.swing.JTextField hBazlama;
    private javax.swing.JTextField hCokelat;
    private javax.swing.JTextField hGozleme;
    private javax.swing.JTextField hKeju;
    private javax.swing.JTextField hOriginal;
    private javax.swing.JTextField hPita;
    private javax.swing.JTextField hRamazan;
    private javax.swing.JTextField hSimit;
    private javax.swing.JTextField hYufka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jumlah;
    private javax.swing.JRadioButton keju;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembali;
    private javax.swing.JButton kurang;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JRadioButton original;
    private javax.swing.JRadioButton pita;
    private javax.swing.JRadioButton ramazan;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton simit;
    private javax.swing.JTextField stlhDiskon;
    private javax.swing.JButton tambah;
    private javax.swing.ButtonGroup topping;
    private javax.swing.JButton total;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txttotal;
    private javax.swing.JRadioButton yufka;
    // End of variables declaration//GEN-END:variables
}
