/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soal2SPP;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class spp extends javax.swing.JFrame {

    /**
     * Creates new form spp
     */
    
    private ArrayList<String> daftarBulanLunas = new ArrayList<>();
     
    private DefaultTableModel tableModel;
    public spp() {
        initComponents();
        this.setLocationRelativeTo(null);
        total.setEditable(false);
        status.setEditable(false);
        
        tableModel = new DefaultTableModel(new String[]{"Nama", "Bulan", "Jumlah SPP", "Status"}, 0);
        tabelData.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pTengah = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spp = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        januari = new javax.swing.JCheckBox();
        februari = new javax.swing.JCheckBox();
        maret = new javax.swing.JCheckBox();
        april = new javax.swing.JCheckBox();
        mei = new javax.swing.JCheckBox();
        juni = new javax.swing.JCheckBox();
        juli = new javax.swing.JCheckBox();
        agustus = new javax.swing.JCheckBox();
        september = new javax.swing.JCheckBox();
        oktober = new javax.swing.JCheckBox();
        november = new javax.swing.JCheckBox();
        desember = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        riwayat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAtas.setBackground(new java.awt.Color(30, 42, 94));
        pAtas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 103, 156), 3));

        jLabel1.setText("jLabel1");
        pAtas.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Schadow BT", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("APLIKASI PEMBAYARAN SPP");
        pAtas.add(jLabel2);

        jLabel3.setText("jLabel3");
        pAtas.add(jLabel3);

        getContentPane().add(pAtas, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(30, 42, 94));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 103, 156), 3));
        jPanel6.setPreferredSize(new java.awt.Dimension(666, 60));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        pTengah.setBackground(new java.awt.Color(124, 147, 195));
        pTengah.setPreferredSize(new java.awt.Dimension(666, 500));
        pTengah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(104, 130, 186));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 94), 3));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBackground(new java.awt.Color(124, 147, 195));

        jLabel4.setText("Nama         :");

        jLabel6.setText("SPP/Bulan  :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(125, 125, 125)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel6)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(124, 147, 195));

        jLabel5.setText("SPP/Bulan  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(spp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        pTengah.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 50));

        jPanel4.setBackground(new java.awt.Color(124, 147, 195));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 94), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(150, 168, 206));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Bulan      :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        januari.setText("Januari");
        jPanel5.add(januari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        februari.setText("Februari");
        jPanel5.add(februari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        maret.setText("Maret");
        jPanel5.add(maret, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        april.setText("April");
        jPanel5.add(april, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        mei.setText("Mei");
        jPanel5.add(mei, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        juni.setText("Juni");
        jPanel5.add(juni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        juli.setText("Juli");
        jPanel5.add(juli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        agustus.setText("Agustus");
        jPanel5.add(agustus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        september.setText("September");
        jPanel5.add(september, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        oktober.setText("Oktober");
        jPanel5.add(oktober, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        november.setText("November");
        jPanel5.add(november, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        desember.setText("Desember");
        jPanel5.add(desember, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 160));

        jLabel8.setText("Status  :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel9.setText("Total   :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));
        jPanel4.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 130, -1));
        jPanel4.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 130, -1));

        riwayat.setText("Riwayat");
        riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatActionPerformed(evt);
            }
        });
        jPanel4.add(riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        pTengah.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 630, 200));

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Bulan", "Total Bayar", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelData);

        pTengah.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 500, 140));

        getContentPane().add(pTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(nama.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
    }
        else if(spp.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Masukkan jumlah spp terlebih dahulu", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(!(januari.isSelected() || februari.isSelected() || maret.isSelected() || 
                april.isSelected() || mei.isSelected() || juni.isSelected() || juli.isSelected() ||
                agustus.isSelected() || september.isSelected() || oktober.isSelected() ||
                november.isSelected() || desember.isSelected())){
            JOptionPane.showMessageDialog(this, "Pilih setidaknya satu bulan yang harus dibayar.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        if (!isSppValid()) {
            JOptionPane.showMessageDialog(this, "Jumlah SPP harus berupa angka yang valid dan tidak boleh negatif.", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
        String namaInput = nama.getText();
    double SPP = Double.parseDouble(spp.getText());
    daftarBulanLunas.clear();
    
    StringBuilder bulanLunas = new StringBuilder();
    int jumlahBulanDipilih = 0;
        
        if (januari.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Januari, ");
            daftarBulanLunas.add("Januari");
            januari.setEnabled(false);
        }
        if (februari.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Februari, ");
            daftarBulanLunas.add("Februari");
            februari.setEnabled(false);
        } 
        if (maret.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Maret, ");
            daftarBulanLunas.add("Maret");
            maret.setEnabled(false);
        } 
        if (april.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("April, ");
            daftarBulanLunas.add("April");
            april.setEnabled(false);
        }
        if (mei.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Mei, ");
            daftarBulanLunas.add("Mei");
            mei.setEnabled(false);
        }
        if (juni.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Juni, ");
            daftarBulanLunas.add("Juni");
            juni.setEnabled(false);
        }
        if (juli.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Juli, ");
            daftarBulanLunas.add("Juli");
            juli.setEnabled(false);
        }
        if (agustus.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Agustus, ");
            daftarBulanLunas.add("Agustus");
            agustus.setEnabled(false);
        }
        if (september.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("September, ");
            daftarBulanLunas.add("September");
            september.setEnabled(false);
        }
        if (oktober.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Oktober, ");
            daftarBulanLunas.add("Oktober");
            oktober.setEnabled(false);
        }
        if (november.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("November, ");
            daftarBulanLunas.add("November");
            november.setEnabled(false);
        }
        if (desember.isSelected()) {
            jumlahBulanDipilih++;
            bulanLunas.append("Desember, ");
            daftarBulanLunas.add("Desember");
            desember.setEnabled(false);
        }
        if (bulanLunas.length() > 0) {
        bulanLunas.setLength(bulanLunas.length() - 2);
    }
        
        double totalPembayaran = jumlahBulanDipilih * SPP; 

        String statusPembayaran = jumlahBulanDipilih == 12 ? "Lunas" : "Menunggak";
        tableModel.setRowCount(0); // Hapus data lama
    tableModel.addRow(new Object[]{namaInput, bulanLunas.toString(), totalPembayaran, statusPembayaran});

    total.setText(String.format("Rp %.0f", totalPembayaran));
    status.setText(statusPembayaran);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatActionPerformed
        // TODO add your handling code here:
        StringBuilder riwayatPembayaran = new StringBuilder("=== Riwayat Pembayaran ===\n");
          // Loop melalui data di tabel
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String namaSiswa = tableModel.getValueAt(i, 0).toString();
            String bulanBayar = tableModel.getValueAt(i, 1).toString();
            String jumlahSPP = tableModel.getValueAt(i, 2).toString();
            String statusBayar = tableModel.getValueAt(i, 3).toString();

            riwayatPembayaran.append("Nama: ").append(namaSiswa)
                    .append("\nBulan: ").append(bulanBayar)
                    .append("\nJumlah SPP: ").append(jumlahSPP)
                    .append("\nStatus: ").append(statusBayar)
                    .append("\n----------------------\n");
        }

        // Tampilkan riwayat di JOptionPane
        JOptionPane.showMessageDialog(null, riwayatPembayaran.toString(), "Riwayat Pembayaran", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_riwayatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        januari.setSelected(false);
        januari.setEnabled(true);

        februari.setSelected(false);
        februari.setEnabled(true);

        maret.setSelected(false);
        maret.setEnabled(true);

        april.setSelected(false);
        april.setEnabled(true);

        mei.setSelected(false);
        mei.setEnabled(true);

        juni.setSelected(false);
        juni.setEnabled(true);

        juli.setSelected(false);
        juli.setEnabled(true);

        agustus.setSelected(false);
        agustus.setEnabled(true);

        september.setSelected(false);
        september.setEnabled(true);

        oktober.setSelected(false);
        oktober.setEnabled(true);

        november.setSelected(false);
        november.setEnabled(true);

        desember.setSelected(false);
        desember.setEnabled(true);

        // Reset text fields
        nama.setText("");
        spp.setText("");
        total.setText("");
        status.setText("");

        // Reset tabel
        tableModel.setRowCount(0); // Hapus data pada tabel
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Ingin keluar?","Keluar",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
         private boolean isSppValid() {
        try {
            double SPP = Double.parseDouble(spp.getText());
            return SPP >= 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
     private void tampilkanDaftarBulanLunas() {
        StringBuilder daftarLunas = new StringBuilder("=================================\nDaftar Bulan yang Sudah Dibayar\n=================================\n");
        for (String bulan : daftarBulanLunas) {
            daftarLunas.append("| "+bulan +" (Lunas)"+ "\n-----------------------------------\n");
        }
            JOptionPane.showMessageDialog(this, daftarLunas.toString(), "Riwayat Pembayaran", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agustus;
    private javax.swing.JCheckBox april;
    private javax.swing.JCheckBox desember;
    private javax.swing.JCheckBox februari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox januari;
    private javax.swing.JCheckBox juli;
    private javax.swing.JCheckBox juni;
    private javax.swing.JCheckBox maret;
    private javax.swing.JCheckBox mei;
    private javax.swing.JTextField nama;
    private javax.swing.JCheckBox november;
    private javax.swing.JCheckBox oktober;
    private javax.swing.JPanel pAtas;
    private javax.swing.JPanel pTengah;
    private javax.swing.JButton riwayat;
    private javax.swing.JCheckBox september;
    private javax.swing.JTextField spp;
    private javax.swing.JTextField status;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
